[tool.black]
line-length = 79
target-version = ['py38', 'py39', 'py310']
preview = true  # Enables experimental formatting, including better string breaking
skip-string-normalization = false
exclude = '''
/(
    \.git
  | \.venv
  | env
  | build
  | dist
  | site-packages
  | venv
)/
'''

[tool.flake8]
max-line-length = 79
ignore = ["E203", "W503"]  # Black-compatible rules
exclude = [".git", "__pycache__", ".venv", "env", "build", "dist", "site-packages", "venv"]
